/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:dd96aa89-f23d-499e-ab14-d27006f385a0",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_Tn77Uzwxb",
    "aws_user_pools_web_client_id": "5r1kst3aoqh0m60bgn317hk16s",
    "oauth": {}
};


export default awsmobile;
